version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: install awscli
          command: sudo pip install awscli

      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            aws configure set default.region us-east-1
            pwd
            ls -al
	    ls -la
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to the S3
          command: |
            aws s3 cp codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${S3_BUCKET_ADDR}/deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip

